# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Amneen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Amneen
   pod 'Firebase/Analytics'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'ShimmerSwift'
   pod ‘IQKeyboardManagerSwift’

end
